const products = [
    {
        id: 1,
        name: "Toyota Corolla",
        url: require ('./Image/Deal1.png'),
        category: "car",
        price: "₦1,800,000",
        location: "Ikeja, Lagos",
    },
    {
        id: 2,
        name: "Apple iPhone",
        url: require ('./Image/Deal2.png'),
        category: "Phone",
        price: "₦1,200,000",
        location: "Ikeja, Lagos",
    },
    {
        id: 3,
        name: "Honda Accord",
        url: require ('./Image/Deal3.png'),
        category: "car",
        price: "₦1,520,000",
        location: "Ikeja, Lagos",
    },
    {
        id: 4,
        name: "Toyota Camry",
        url: require ('./Image/Deal4.png'),
        category: "car",
        price: "₦1,750,000",
        location: "Ikeja, Lagos",
    },
    {
        id: 5,
        name: "Untitled",
        url: require ('./Image/Deal5.png'),
        category: "link",
        price: "Untitled.com",
        location: "Sponsored Ads",
    },
    {
        id: 6,
        name: "Samsung Galaxy Note",
        url: require ('./Image/Deal6.png'),
        category: "phone",
        price: "₦600,000",
        location: "Ikeja, Lagos",
    },
    {
        id: 7,
        name: "2 - bedroom Apartment",
        url: require ('./Image/Deal7.png'),
        category: "House",
        price: "₦1,000,000",
        location: "Ikeja,Lagos",
    },
    {
        id: 8,
        name: "Honda Civic",
        url: require ('./Image/Deal8.png'),
        category: "car",
        price: "₦1,650,000",
        location: "Ikeja, Lagos",
    },
    {
        id: 9,
        name: "Short Gown",
        url: require ('./Image/Deal9.png'),
        category: "cloth",
        price: "₦62,000",
        location: "Ikeja, Lagos",
    },
    {
        id: 10,
        name: "Sneakers",
        url: require ('./Image/Deal10.png'),
        category: "shoe",
        price: "₦1,800,000",
        location: "Ikeja, Lagos",
    },
    {
        id: 11,
        name: "Hyundai",
        url: require ('./Image/Deal11.png'),
        category: "car",
        price: "₦1,800,000",
        location: "Ikeja, Lagos",
    },
    {
        id: 12,
        name: "Toyota Corolla",
        url: require ('./Image/Deal12.png'),
        category: "car",
        price: "₦1,800,000",
        location: "Ikeja, Lagos",
    },
]

export default products;